### ISSUE TITLE
Affichage du contenu de la route enfant mais pas de la route parente

### ISSUE THREAD

**Issue by LeoTexier** [dixplo/BigBrainsBoard-Project#30]
J'essai d'afficher les stories d'un projet, cependant, après avoir créer ma route projects/stories.js, j'ai toujours le contenu de la route projects (qui affiche la liste de tous les projets).

Comment faire pour afficher unique le résultat de ma route projects/stories.js ?

Merci.

**Comment by jcheron** [comment]
https://github.com/dixplo/BigBrainsBoard-Project/blob/a07b686eb9d08642a340d71cef3b64575681734c/app/router.js#L17

- `routes/projects.js` devrait être déplacé/renommé en `routes/projects/index.js`
- `templates/projects.hbs` devrait être déplacé/renommé en `templates/projects/index.hbs`

**Comment by LeoTexier** [comment]
Merci beaucoup !

**Comment by LeoTexier** [comment]
Petit problème qui survient de nouveau après la modification des .js et .hbs:

Quand on appel le projects/add, la console retourne des erreurs quand on interagi avec n'importe lequel des éléments du templates...

Quand l'utilisateur ne rempli pas un champ et qu'il valide:
`index.js:163 Uncaught Error: Assertion Failed: Cannot call set with 'error' on an undefined object.
    at assert (index.js:163)
    at Object.set (metal.js:2915)
    at Class.backToProj (new.js:29)
    at Class.triggerEvent (router.js:1295)
    at PrivateRouter.triggerEvent (router.js:175)
    at PrivateRouter.trigger (router_js.js:2196)
    at Class.send (router.js:515)
    at Class.send (action_handler.js:184)
    at glimmer.js:8544
    at instrument (index.js:141)`

Quand l'utilisateur essai de rentrer un nom de projet:
`new.js:12 Uncaught TypeError: Cannot read property 'name' of null
    at Class.addNew (new.js:12)
    at Class.triggerEvent (router.js:1295)
    at PrivateRouter.triggerEvent (router.js:175)
    at PrivateRouter.trigger (router_js.js:2196)
    at Class.send (router.js:515)
    at Class.send (action_handler.js:184)
    at glimmer.js:8544
    at instrument (index.js:141)
    at glimmer.js:8543
    at Backburner._run (backburner.js:1010)`

**Comment by jcheron** [comment]
Elle est fermée l'issue là...
C'est résolu ?

**Comment by LeoTexier** [comment]
Non le fais d'avoir changer les nom de fichiers à générer des erreurs d'objet indéfini.

**Comment by LeoTexier** [comment]
Ce genre d'erreur est effectif que dans l'action projects/new

**Comment by jcheron** [comment]
Il suffit que le model hook de la route `projects/new` retourne un objet:

```javascript
  model(){
    return EmberObject.create();
  }
```

https://github.com/dixplo/BigBrainsBoard-Project/blob/936b9fe48dd19b32ebdf120b715984637d7a17a1/app/routes/projects/new.js#L6

Bon :birthday:

**Comment by LeoTexier** [comment]
Merci beaucoup !
