### ISSUE TITLE
Affichage des stories

### ISSUE THREAD

**Issue by LeoTexier** [dixplo/BigBrainsBoard-Project#31]
L'affichage des stories ne marche pas, le problème pourrait surement venir des models: story et project.

Story:
`export default Model.extend({
  code:DS.attr('string'), // propriet� persistente
  descriptif:DS.attr('string'), // propriet� persistente
  project:DS.belongsTo('project',{inverse:'stories'})
});`

Project:
`export default Model.extend({
  name: DS.attr('string'),
  descriptif: DS.attr('string'), // proprieté persistente
  startDate: DS.attr('string'),
  dueDate: DS.attr('string'),
  developer: DS.attr(),
  stories:DS.hasMany('story')
});`

**Comment by jcheron** [comment]
Pour faire un lien direct vers le code:
https://github.com/dixplo/BigBrainsBoard-Project/blob/9cd9686f06ef277a1fdb882adf1d5de4dee5d32f/app/models/story.js#L4-L8

**Comment by LeoTexier** [comment]
Je vois pas d'où pourrait venir le problème sinon.

**Comment by jcheron** [comment]
Il est où le code qui ajoute des stories ?

**Comment by LeoTexier** [comment]
https://github.com/dixplo/BigBrainsBoard-Project/blob/8548843c83e042d2d81982119f7f03031b88957e/app/routes/projects/stories/new.js#L1

**Comment by LeoTexier** [comment]
Je pense pas que le problème de l'affichage vienne de l'ajout.

**Comment by jcheron** [comment]
Et quand vous ajoutez, dans Mongo, vous avez bien 
- le project sur chaque story
- les stories pour chaque project ?

**Comment by LeoTexier** [comment]
![ref](https://user-images.githubusercontent.com/55082513/78871653-4b6ead80-7a48-11ea-9416-14af32595690.PNG)

**Comment by LeoTexier** [comment]
J'ai bien la story qui fait réference au projet

**Comment by LeoTexier** [comment]
Et mon projet à bien une liste de stories:
![ref2](https://user-images.githubusercontent.com/55082513/78872056-f67f6700-7a48-11ea-80b4-c2bb713e0ac9.PNG)

**Comment by LeoTexier** [comment]
Ca marche merci
