### ISSUE TITLE
Ajout des tags

### ISSUE THREAD

**Issue by LeoTexier** [dixplo/BigBrainsBoard-Project#33]
Bonjour, je pense avoir fais le nécessaire, cependant je n'arrive pas à avoir:
-Dans mes tags, la référence de la story.
![1](https://user-images.githubusercontent.com/55082513/79978273-f39c6180-849f-11ea-9914-1fd564f3f752.PNG)

-Dans mes stories, la liste de tags de la story.
![2](https://user-images.githubusercontent.com/55082513/79978303-fe56f680-849f-11ea-86f5-24e67ba27a97.PNG)

Alors que pourtant dans les models, j'ai bien fait ce qu'il fallait:
https://github.com/dixplo/BigBrainsBoard-Project/blob/e9d7c8d3ac227fb1d86c65228e6343c6916c60f3/app/models/story.js#L8
https://github.com/dixplo/BigBrainsBoard-Project/blob/e9d7c8d3ac227fb1d86c65228e6343c6916c60f3/app/models/tag.js#L6

**Comment by LeoTexier** [comment]
Problème réglé pour les tags, mais toujours pas de liste de tags pour la story.

**Comment by jcheron** [comment]
Un tag n'est pas présent dans une seule story, mais utilisable dans plusieurs...
Regardez, le tag `help wanted`, on peut l'utiliser dans plusieurs issues github.

L'association ci-dessous est donc fausse :
https://github.com/dixplo/BigBrainsBoard-Project/blob/e9d7c8d3ac227fb1d86c65228e6343c6916c60f3/app/models/tag.js#L6

**Comment by LeoTexier** [comment]
Du coup comment je peux faire ?

**Comment by jcheron** [comment]
Et bien le tag n'a pas de story (aucune relation),
et la story a des tags

**Comment by LeoTexier** [comment]
J'arrive pas obtenir un tag lié à une story. Vous savez comment je peux faire ?

J'ai déjà ça:
https://github.com/dixplo/BigBrainsBoard-Project/blob/e9d7c8d3ac227fb1d86c65228e6343c6916c60f3/app/models/story.js#L8

Et ça:
https://github.com/dixplo/BigBrainsBoard-Project/blob/e9d7c8d3ac227fb1d86c65228e6343c6916c60f3/app/routes/projects/stories/tags/new.js#L12

**Comment by jcheron** [comment]
C'est cette ligne là qui est bizarre:
https://github.com/dixplo/BigBrainsBoard-Project/blob/e9d7c8d3ac227fb1d86c65228e6343c6916c60f3/app/routes/projects/stories/tags/new.js#L13
Où est-ce que vous avez vu un `tag` dans la story ?
C'est des `tags` donc une collection, et il faut ajouter le nouveau tag dedans:
```javascript
get(story,'tags').pushObject(tag);
```

**Comment by LeoTexier** [comment]
A d'accord, je connaissais pas le .pushObject(), merci beaucoup.
