### ISSUE TITLE
Adapter inadapté

### ISSUE THREAD

**Issue by jcheron** [dixplo/BigBrainsBoard-Project#34]
https://github.com/dixplo/BigBrainsBoard-Project/blob/53cc0ac7aa12b1ef1c721056222db182e9569909/app/adapters/application.js#L1

Pour le local storage, c'est:
```javascript
import Adapter from 'ember-local-storage/adapters/local';
 
export default Adapter.extend({
  modelNamespace: 'boards'
});
```

Même chose pour le serializer...

**Comment by LeoTexier** [comment]
C'est bizarre j'ai bien installé le module mais il trouve pas apparemment.
