### ISSUE TITLE
Confirm remove with modal (for projects)

### ISSUE THREAD

**Issue by Nemoo0** [dixplo/BigBrainsBoard-Project#4]
Comment passer en paramètre le projet en étant en dehors du {{each}} ?

**Comment by jcheron** [comment]
Dans le template de la modale, vous pouvez faire une référence à un objet:
```html
<div class="ui modal">
<p>Confirmez la suppression de {{model.toDelete.identity}}</p>
</div>
```
et vous initialisez cet objet quand l'action de suppression est appelée:
```javascript
confirmDelete(model,dev){
    model.set('toDelete',dev);
    //Afficher la modale
}
```
