### ISSUE TITLE
Remove Developper

### ISSUE THREAD

**Issue by LeoTexier** [dixplo/BigBrainsBoard-Project#5]
L'application ne supprime pas les développeurs en appelant l'action concernée dans la base.
Quand on rafraîchi la page les dev, ceux supprimés sont de nouveaux affichés:

developers.hbs:
```<div class="ui segment"><h3>Developers List</h3>
  {{#each model as |developer|}}
    <div class="ui green segment" id="devSegment">
        {{developer.identity}}
        {{developer.name}}
        {{developer.fname}}
          <div {{action "edit" identity name fname}} style="float:right;" class="ui button">Edit</div>
          <div {{action "remove" developer}} style="float:right;" class="ui button">Remove</div>
          <br>
          <br>
    </div>
    {{/each}}
</div>

**Comment by LeoTexier** [comment]
developers.js (route):

`export default Route.extend({
  model() {
          return this.get('store').findAll('developer');
      },
  actions:{
    addNew(m,identity, name, fname){
      if(!identity || !name || !fname){

      }
      else{
        let store=this.get('store');
        m.set('content',""); // Sert à mettre les champs vides quand l'ajout est fait
        this.get('store').createRecord('developer',{identity: identity, name: name,fname:fname}).save(); // developer désigne le model
        //developer.save();
      }
    },
    remove(developer){
      developer.deleteRecord();
      developer.save();
    }
  }
});
`

**Comment by jcheron** [comment]
Et les dév concernés ont été créés avec votre appli EmberJs, ou directement avec Mongo ou Compass ?
Ceux créés en dehors d'Ember ne peuvent pas être supprimés compte tenu du système d'identifiants changé.

**Comment by LeoTexier** [comment]
Créer avec Compass mais l'ajout de dev ne marche pas non plus...

Je fais une issue.

**Comment by jcheron** [comment]
> Créer avec Compass mais l'ajout de dev ne marche pas non plus...

Donc normal qu'on ne puisse pas les supprimer avec votre app
